import SignIn from './SignIn';
import SignUp from './SignUp';
import Assets from './Assets';
import Trade from './Trade';
import Pay from './Pay';
import Deposit from './Deposit';
import ProtectedPages from './ProtectedPages';
import Partner from './Partner';
import Rating from './Rating';
import Feedback from './Feedback';
import LearnMore from './LearnMore';
export { SignIn, SignUp, Assets, Trade, Pay, Deposit, ProtectedPages, Partner, Rating, Feedback, LearnMore };
